import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { BadgeCheck, Banknote, BriefcaseBusiness, Megaphone, Settings2, ShieldAlert, Sparkles, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getAdminWorkspace, reviewKyc, reviewPayment, reviewWithdrawal, runAdminAction } from "@/lib/marketplace.functions";

export const Route = createFileRoute("/_authenticated/admin")({
  head: () => ({ meta: [
    { title: "Admin Control — SkillEarn Assam" },
    { name: "description", content: "Manage SkillEarn Assam providers, KYC, bookings, payments and safety." },
    { property: "og:title", content: "Admin Control — SkillEarn Assam" },
    { property: "og:description", content: "Secure SkillEarn Assam operations dashboard." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary" },
  ] }),
  component: AdminPage,
});

type AdminData = Awaited<ReturnType<typeof getAdminWorkspace>>;
function AdminPage() {
  const load = useServerFn(getAdminWorkspace); const review = useServerFn(reviewKyc);
  const verifyPayment = useServerFn(reviewPayment); const processWithdrawal = useServerFn(reviewWithdrawal);
  const adminAction = useServerFn(runAdminAction);
  const [data,setData] = useState<AdminData | null>(null); const [message,setMessage] = useState("");
  const refresh = async () => setData(await load());
  const act = async (payload: { action:"method"|"commission"|"feature"|"report"|"dispute"|"refund"|"coupon"|"plan"|"service"|"announcement"; id?:string; status?:string; name?:string; value?:number; secondary?:number; text?:string; enabled?:boolean }, success: string) => { try { await adminAction({ data: payload }); setMessage(success); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Admin change could not be saved."); } };
  useEffect(() => { refresh().catch(() => setMessage("Admin access is required.")); }, [load]);
  if (!data) return <AppShell title="Admin control" eyebrow="Protected operations"><p className="glass-panel rounded-xl p-6">{message || "Loading secure controls…"}</p></AppShell>;
  const pendingKyc = data.kyc.filter((item) => item.status === "pending");
  return <AppShell title="Admin control" eyebrow="Protected operations">
    {message && <p className="mb-5 rounded-md border border-glass-border bg-glass p-3 text-sm">{message}</p>}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={UsersRound} label="Customers" value={data.profiles.length} /><Metric icon={BriefcaseBusiness} label="Providers" value={data.providers.length} /><Metric icon={BadgeCheck} label="KYC pending" value={pendingKyc.length} /><Metric icon={Banknote} label="Bookings" value={data.bookings.length} /></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="glass-panel rounded-xl p-5"><h2 className="font-display text-xl font-bold">KYC review queue</h2><div className="mt-4 grid gap-3">{pendingKyc.length ? pendingKyc.map((item) => <article key={item.id} className="rounded-lg border border-glass-border bg-glass p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Provider verification</p><p className="text-xs text-muted-foreground">Submitted {new Date(item.created_at).toLocaleDateString("en-IN")}</p></div><Badge variant="outline">pending</Badge></div><div className="mt-3 flex gap-2"><Button size="sm" variant="light" onClick={async () => { await review({ data: { providerUserId:item.provider_user_id,approved:true,reason:"" } }); await refresh(); }}>Approve</Button><Button size="sm" variant="ghost" onClick={async () => { await review({ data: { providerUserId:item.provider_user_id,approved:false,reason:"Documents need correction." } }); await refresh(); }}>Reject</Button></div></article>) : <p className="py-8 text-center text-sm text-muted-foreground">No pending KYC reviews.</p>}</div></div><div className="grid gap-4"><Summary title="Money controls" lines={[`Payments: ${data.payments.length}`,`Withdrawals: ${data.withdrawals.length}`,`Commission: ${data.commission?.commission_percent ?? 10}%`,`Minimum withdrawal: ₹${data.commission?.minimum_withdrawal ?? 500}`]} /><Summary title="Trust & safety" lines={[`Reports: ${data.reports.length}`,`Disputes: ${data.disputes.length}`,`Featured providers: ${data.providers.filter((item) => item.is_featured).length}`]} /><Summary title="Growth tools" lines={[`Coupons: ${data.coupons.length}`,`Plans: ${data.plans.length}`,`Payment methods configured: ${data.methods.filter((item) => item.is_enabled).length}`]} /></div></section>
    <section className="mt-5 glass-panel rounded-xl p-5"><div className="flex items-center gap-2"><ShieldAlert className="text-primary" /><h2 className="font-display text-xl font-bold">Operational overview</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Summary title="Pending bookings" lines={[String(data.bookings.filter((item) => item.status === "pending").length)]} /><Summary title="Pending payments" lines={[String(data.payments.filter((item) => item.status === "pending").length)]} /><Summary title="Open complaints" lines={[String(data.reports.filter((item) => item.status === "open").length + data.disputes.filter((item) => item.status === "open").length)]} /></div></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="glass-panel rounded-xl p-5"><h2 className="font-display text-xl font-bold">Payment verification</h2><div className="mt-4 grid gap-3">{data.payments.filter((item) => item.status === "pending").map((item) => <article key={item.id} className="rounded-lg border border-glass-border p-4"><p className="font-semibold">₹{item.amount} · {item.method}</p><p className="text-xs text-muted-foreground">Reference: {item.transaction_reference || "Not provided"}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="light" onClick={async () => { await verifyPayment({ data:{ paymentId:item.id,approved:true,note:"Verified by admin" } }); await refresh(); }}>Verify & receipt</Button><Button size="sm" variant="ghost" onClick={async () => { await verifyPayment({ data:{ paymentId:item.id,approved:false,note:"Payment could not be verified" } }); await refresh(); }}>Reject</Button></div></article>)}</div></div><div className="glass-panel rounded-xl p-5"><h2 className="font-display text-xl font-bold">Withdrawal approvals</h2><div className="mt-4 grid gap-3">{data.withdrawals.filter((item) => item.status === "pending" || item.status === "approved").map((item) => <article key={item.id} className="rounded-lg border border-glass-border p-4"><p className="font-semibold">₹{item.amount} · {item.method}</p><Badge className="mt-2" variant="outline">{item.status}</Badge><div className="mt-3 flex gap-2">{item.status === "pending" && <Button size="sm" variant="light" onClick={async () => { await processWithdrawal({ data:{ withdrawalId:item.id,status:"approved",note:"Approved" } }); await refresh(); }}>Approve</Button>}{item.status === "approved" && <Button size="sm" variant="light" onClick={async () => { await processWithdrawal({ data:{ withdrawalId:item.id,status:"paid",note:"Payout completed" } }); await refresh(); }}>Mark paid</Button>}<Button size="sm" variant="ghost" onClick={async () => { await processWithdrawal({ data:{ withdrawalId:item.id,status:"rejected",note:"Rejected by admin" } }); await refresh(); }}>Reject</Button></div></article>)}</div></div></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-3"><AdminForm title="Marketplace settings" icon={Settings2} onSubmit={(form) => act({ action:"commission", id:String(data.commission?.id), value:Number(form.get("commission")), secondary:Number(form.get("minimum")) },"Money settings updated.")}><input name="commission" type="number" min="0" max="100" defaultValue={data.commission?.commission_percent ?? 10} required className="field"/><input name="minimum" type="number" min="1" defaultValue={data.commission?.minimum_withdrawal ?? 500} required className="field"/></AdminForm><AdminForm title="Add growth tool" icon={Sparkles} onSubmit={(form) => { const action=String(form.get("kind")) as "coupon"|"plan"|"service"; return act({ action, name:String(form.get("name")), value:Number(form.get("value")), secondary:Number(form.get("secondary")), text:String(form.get("text")) },`${action} created.`); }}><select name="kind" className="field"><option value="coupon">Coupon</option><option value="plan">Subscription plan</option><option value="service">Service category</option></select><input name="name" required placeholder="Name or coupon code" className="field"/><input name="value" type="number" min="0" placeholder="Discount % or price" className="field"/><input name="secondary" type="number" min="0" placeholder="Minimum booking" className="field"/><input name="text" placeholder="Description or expiry date" className="field"/></AdminForm><AdminForm title="Publish announcement" icon={Megaphone} onSubmit={(form) => act({ action:"announcement", name:String(form.get("title")), text:String(form.get("message")), status:String(form.get("audience")) },"Announcement published.")}><input name="title" required placeholder="Title" className="field"/><input name="message" required placeholder="Message" className="field"/><select name="audience" className="field"><option value="all">Everyone</option><option value="customer">Customers</option><option value="provider">Providers</option></select></AdminForm></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><Queue title="Trust cases" items={[...data.reports.map((item) => ({ id:item.id,type:"report" as const,label:item.reason,status:item.status })),...data.disputes.map((item) => ({ id:item.id,type:"dispute" as const,label:item.reason,status:item.status }))]} act={act}/><Queue title="Refund requests" items={data.refunds.map((item) => ({ id:item.id,type:"refund" as const,label:`₹${item.amount} · ${item.reason}`,status:item.status }))} act={act}/></section>
    <section className="mt-5 glass-panel rounded-xl p-5"><h2 className="font-display text-xl font-bold">Payment methods</h2><div className="mt-4 flex flex-wrap gap-3">{data.methods.map((method) => <Button key={method.id} variant={method.is_enabled ? "light" : "glass"} onClick={() => act({ action:"method",id:method.id,enabled:!method.is_enabled },`${method.label} ${method.is_enabled ? "disabled" : "enabled"}.`)}>{method.label} · {method.is_enabled ? "ON" : "OFF"}</Button>)}</div></section>
  </AppShell>;
}
function Metric({icon:Icon,label,value}:{icon:typeof UsersRound;label:string;value:number}) { return <div className="glass-panel rounded-xl p-5"><Icon className="size-5 text-primary" /><p className="mt-4 text-xs uppercase text-muted-foreground">{label}</p><p className="font-display text-2xl font-bold">{value}</p></div>; }
function Summary({title,lines}:{title:string;lines:string[]}) { return <div className="glass-panel rounded-xl p-5"><h3 className="font-display font-bold">{title}</h3>{lines.map((line) => <p key={line} className="mt-2 text-sm text-muted-foreground">{line}</p>)}</div>; }
function AdminForm({title,icon:Icon,onSubmit,children}:{title:string;icon:typeof Settings2;onSubmit:(form:FormData)=>Promise<void>;children:React.ReactNode}) { return <form className="glass-panel rounded-xl p-5" onSubmit={async (event)=>{event.preventDefault();await onSubmit(new FormData(event.currentTarget));event.currentTarget.reset();}}><div className="flex items-center gap-2"><Icon className="text-primary"/><h2 className="font-display font-bold">{title}</h2></div><div className="mt-4 grid gap-3">{children}<Button type="submit" variant="light">Save</Button></div></form>; }
function Queue({title,items,act}:{title:string;items:{id:string;type:"report"|"dispute"|"refund";label:string;status:string}[];act:(payload:{action:"report"|"dispute"|"refund";id:string;status:string;text?:string},success:string)=>Promise<void>}) { return <div className="glass-panel rounded-xl p-5"><h2 className="font-display text-xl font-bold">{title}</h2><div className="mt-4 grid gap-3">{items.length ? items.map((item)=><article key={`${item.type}-${item.id}`} className="rounded-lg border border-glass-border p-4"><p className="font-semibold">{item.label}</p><Badge className="mt-2" variant="outline">{item.status}</Badge><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="light" onClick={()=>act({action:item.type,id:item.id,status:item.type==="refund"?"processed":"resolved",text:"Reviewed by admin"},"Case resolved.")}>Resolve</Button><Button size="sm" variant="ghost" onClick={()=>act({action:item.type,id:item.id,status:"rejected",text:"Rejected by admin"},"Case rejected.")}>Reject</Button></div></article>) : <p className="text-sm text-muted-foreground">No pending records.</p>}</div></div>; }